### PR TITLE
BV-629: Use celery.decorators.tasks decorator

### PR DESCRIPTION
**Pull request by AndreyLykhoman**
**Description:**
Fixed problem with sending emails. For that:

Use celery.decorators.tasks instead of lms.CELERY_APP.task

**Tasks:**
https://youtrack.raccoongang.com/issue/BV-629

**The demo was shown**

### CODE REVIEW

**Review by NikolayBorovenskiy — APPROVED** [review]
Bless your struggles @AndreyLykhoman. Keep fingers crossed for you buddy 🙂

**Comment by idegtiarov** [comment]
@AndreyLykhoman what about the new version of the xblock in setup.py ?

**Review by idegtiarov — CHANGES_REQUESTED** [review]
@AndreyLykhoman what about the new version of the xblock in setup.py ?

**Comment by AndreyLykhoman** [comment]
@idegtiarov 
I've forgotten about this. Thanks a lot!
The version of the package is increased.

**Review by idegtiarov — APPROVED** [review]

**Pull request merged**
